### PR TITLE
new workflow to build and push docker image

### PR DESCRIPTION
**Pull request by TejasMorbagal**
[Description of PR]

This PR introduces a new workflow which builds and pushes a new xcube docker image. This is a workaround for the timeout errors in unit test which blocks us from making a release.

Checklist:

~* [ ] Add unit tests and/or doctests in docstrings~
~* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions~
~* [ ] New/modified features documented in `docs/source/*`~
* [ ] Changes documented in `CHANGES.md`
~* [ ] GitHub CI passes~
~* [ ] AppVeyor CI passes~
~* [ ] Test coverage remains or increases (target 100%)~

### CODE REVIEW

**Review by thomasstorm — APPROVED** [review]
Looks good!

**Review by TonioF — COMMENTED** [review]
The script itself looks good, but what about that update-version part? Shouldn't that also be executed when a docker image is built?

**Comment by TejasMorbagal** [comment]
> The script itself looks good, but what about that update-version part? Shouldn't that also be executed when a docker image is built?

My thoughts were that the ArgoCD image updater automatically updates the .argo files which is then used by deployment to fetch the new docker image. We no longer use docker image tags or hash directly. Do you agree on this?

**Comment by TonioF** [comment]
> > The script itself looks good, but what about that update-version part? Shouldn't that also be executed when a docker image is built?
> 
> My thoughts were that the ArgoCD image updater automatically updates the .argo files which is then used by deployment to fetch the new docker image. We no longer use docker image tags or hash directly. Do you agree on this?

If we don't need this, it's fine. But shouldn't the update section be removed from the other workflow then, too?

**Review by pont-us — APPROVED** [review]

**Pull request merged**
