### PR TITLE
Add function select_label_subset()

### PR DESCRIPTION
**Pull request by forman**
Added a new function `xcube.core.select.select_label_subset()` that is used to select dataset labels along a given dimension using user-defined predicate functions.

Checklist:

* [x] Add unit tests and/or doctests in docstrings
* [x] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] ~New/modified features documented in `docs/source/*`~
* [x] Changes documented in `CHANGES.md`
* [x] AppVeyor CI passes
* [x] Test coverage remains or increases (target 100%)

### CODE REVIEW

**Review by TonioF — COMMENTED** [review]
The functionality works. However, I'd like a test that explains what happens when you pass different predicates to different variables - an admittedly advanced case that nevertheless should work as expected.

**Review by AliceBalfanz — CHANGES_REQUESTED** [review]
I do not understand, how I can test this PR. It would also be nice to get documentation for this new function.

**Comment by forman** [comment]
> I do not understand, how I can test this PR. It would also be nice to get documentation for this new function.

The function body comprises 50 lines of documentation + >350 lines of test code.
However, I will provide a usage example.

**Comment by forman** [comment]
> The functionality works. However, I'd like a test that explains what happens when you pass different predicates to different variables - an admittedly advanced case that nevertheless should work as expected.

I agre and I'll add an appropriate test.

**Comment by forman** [comment]
FYI @AliceBalfanz I removed you as a reviewer, because of your absence and functionality is needed until tomorrow.

**Review by TonioF — APPROVED** [review]

**Pull request merged**
