### PR TITLE
Add generator service documentation

### LINKED ISSUE #507: Document the xcube gen service
The standard xcube documentation should include an overview of the structure and operation of the xcube gen service. (For detailed usage instructions we already have the example notebooks.)

### PR DESCRIPTION
**Pull request by pont-us**
Closes #507.

This PR adds documentation for the gen2 service, along with an example notebook demonstrating usage of the gen2 REST API.

### CODE REVIEW

**Review by forman — APPROVED** [review]
Excellent, thanks!

**Comment by forman** [comment]
@pont-us please link to new doc from the main doc's index

**Comment by forman** [comment]
FYI @AliceBalfanz  @dzelge  @TonioF

I'm going to merge this after 21 days.

**Comment by pont-us** [comment]
> FYI @AliceBalfanz @dzelge @TonioF
> 
> I'm going to merge this after 21 days.

Suits me, especially since this PR also fixes some general issues with RTD generation -- if updates are needed due to the recent changes in the generator API, we can open a new PR for that.

**Pull request merged**
