### PR TITLE
Allow running xcube Env with Coiled

### PR DESCRIPTION
**Pull request by forman**
Added lz4 and python-blosc (should be transitive deps anyway), so we can use xcube env on Coiled without modifications

Checklist:

* [x] Add unit tests and/or doctests in docstrings
* ~[ ] Add docstrings and API docs for any new/modified user-facing classes and functions~
* ~[ ] New/modified features documented in `docs/source/*`~
* [x] Changes documented in `CHANGES.md`
* [x] AppVeyor CI passes
* [x] Test coverage remains or increases (target 100%)

### CODE REVIEW

**Comment by forman** [comment]
FYI @AliceBalfanz @pont-us

**Review by TonioF — CHANGES_REQUESTED** [review]
Both packages were not included in my local xcube environment, hence I do not think they are "transitive deps anyway".
What troubles me most though are the many test failures on macos according to appveyor. If these failures are related to these changes (which I strongly assume), I suggest that you create an alternative environment.yml somewhere else and use that one for coiled.

**Comment by forman** [comment]
> If these failures are related to these changes (which I strongly assume)

They are not. xcube main branch has the same issues. @pont-us already reported them yesterday.

**Comment by TonioF** [comment]
> > If these failures are related to these changes (which I strongly assume)
> 
> They are not. xcube main branch has the same issues. @pont-us already reported them yesterday.

I checked whether the errors also appear on the main branch, which they did not, as they are already fixed there. Can you please merge the main branch so we have a complete appveyor check?

**Comment by forman** [comment]
I'll close this as this already way to much effort. Will create a dedicated env for time being.

**Comment by forman** [comment]
Need to reopen, as there is one already dependent on this.

**Review by TonioF — APPROVED** [review]

**Pull request merged**
