### PR TITLE
Forman 139 handle time slice doubles

### PR DESCRIPTION
**Pull request by forman**
### Main objective:

* changed `gen_cube()` also replace existing time slices by using new `xcube.util.timeslice.replace_time_slice()`

### Side objectives:

* deprecated  `append` flag and added `prof` flag in `xcube gen` CLI
* deprecated  `append_mode` kwarg and added `profile_mode` kwarg in `xcube.api.gen_cube()` 

#### New `timeslice` module:

* renamed from module `xcube.util.dsgrow`
* added `replace_time_slice()`
* renamed `get_time_insert_index()` into `find_time_slice()` which now returns a tuple `(time_index, update_mode)`
* added new tests

### CODE REVIEW

**Comment by dzelge** [comment]
@forman i also wonder whether the version tag in CHANGELOG makes sense. We have now a 0.2.0.dev1 version tag. If we release version 0.2.0.dev2 we can't read from the CHANGELOG what was added in comparison to version 0.2.0.dev1.

**Comment by dzelge** [comment]
Curiously, the Travis build is still on fail, though. The unit tests ran fine on Mac but not on Linux. 

 

------------------------

Helge

Brockmann Consult

 

Von: Alicja Balfanz <notifications@github.com> 
Gesendet: Freitag, 23. August 2019 08:05
An: dcs4cop/xcube <xcube@noreply.github.com>
Cc: Helge Dzierzon <helge.dzierzon@brockmann-consult.de>; Review requested <review_requested@noreply.github.com>
Betreff: Re: [dcs4cop/xcube] Forman 139 handle time slice doubles (#161)

 

@AliceBalfanz approved this pull request.

After the fix, it does generate cubes in an expected manner :) Thanks :)

**Comment by forman** [comment]
> @forman i also wonder whether the version tag in CHANGELOG makes sense. We have now a 0.2.0.dev1 version tag. If we release version 0.2.0.dev2 we can't read from the CHANGELOG what was added in comparison to version 0.2.0.dev1.

That's right. I'll indicate the tag name in the CHANGES.md.

**Comment by forman** [comment]
> One test fails (EDIT: on [travis](https://travis-ci.com/dcs4cop/xcube/jobs/227079166)):

I'll take care...

**Comment by forman** [comment]
Argh, also test coverage decreased... no good

**Comment by forman** [comment]
>  The unit tests ran fine on Mac but not on Linux.

It is the way globbing takes place, Win and Mac provide sorted file lists (by intention?), Linux doesn't. I'll fix it

**Comment by forman** [comment]
Tests run green, I'll go and merge!

**Pull request merged**
