### PR TITLE
xcube serve consolidated

### LINKED ISSUE #141: Consolidate cubes to make them much faster
**Is your feature request related to a problem? Please describe.**

Opening larger cubes from OTC Object Storage or AWS S3 takes too long. Analysis has shown that this is caused mainly by the many HTTP requests made for 
* `.zarray` and `.zattrs` metadata files, either by checking for existence or to load them;
* time coordinate chunks if the chunking for time is one (e.g. `chunks={'time': 1, 'lat': 1000, 'lon': 1000)` . 

**Describe the solution you'd like**

"Consolidate" cubes after each append, insert, and overwrite of time slices using `xcube gen`. That includes 
1. calling zarr's [consolidate_metadata](https://zarr.readthedocs.io/en/stable/api/convenience.html#zarr.convenience.consolidate_metadata) function;
2. combine all time chunks into a single so time coordinate variable is never chunked.

TODO

- [x] a new CLI impl. module and public command `consolidate <dataset>` so we can consolidate existing cubes.
- [x] a new API impl. module and public function `consolidate_dataset` 
- [x] call `consolidate_dataset` from `xcube gen` after creating or extending cubes
- [x] in `xcube serve`, use xarray's [open_zarr](http://xarray.pydata.org/en/stable/generated/xarray.open_zarr.html) function with the `consolidated=True` flag.

**Additional context**

CyanoAlert cubes in OTC OBS take up to a few minutes to open, see #131 and https://github.com/dcs4cop/xcube-viewer/issues/61

### PR DESCRIPTION
**Pull request by forman**
After applying this PR, xcube server will recognise remote cubes with consolidated metadata, which should make the access faster.

Please review PR #195 first, **it is a prerequisite for this one!** Note, that when this PR is applied, xcube server will not be able to serve some of the current cubes in DCS4COP. E.g. cube `MSI_L2_VITO_Chla_SPM_31UET_v041-optimized_54x128x128.zarr` is broken w.r.t. to its `.zmetadata` file because of #194.

Closes #141.

### CODE REVIEW

**Comment by forman** [comment]
@AliceBalfanz, yes, this is what has been fixed in #195. You have to `xcube optimize cmems_SPM_DemoCase_v040-optimized.zarr` once more.

**Comment by AliceBalfanz** [comment]
> @AliceBalfanz, yes, this is what has been fixed in #195. You have to `xcube optimize -CI cmems_SPM_DemoCase_v040-optimized.zarr` once more.

Despite doing so, I still get the message e.g. for rbins-cmems-SPM-DemoCase-v040_1x128x256.zarr
`destination buffer too small; expected at least 2696, got 8`
I optimized and pruned all of the rbins cubes as well as our xcube datasets.

**Comment by forman** [comment]
@AliceBalfanz, note you must prune before and optimize after using the PR #195 branch. Have you done this?

**Comment by AliceBalfanz** [comment]
@forman , I have first optimized and then pruned the cubes after PR #195. It was not clear, that pruning had to be done before optimizing...Now the PR #195 is already in the master - if I understand your comment correctly, I cannot fix the cubes anymore, because pruning does not work anymore?

**Comment by AliceBalfanz** [comment]
I have adjusted the show_remote_cubes.py, in order to print out the failing cube paths and the error message of the cubes and not to fail: 

```
    for filepath in sorted(obs_file_system.ls(bucket)):
        if filepath.endswith('.zarr'):
            try:
                # ds = read_cube(f'{endpoint_url}/{filepath}', consolidated=True)
                ds = read_cube(f'{endpoint_url}/{filepath}')
                var_list = list(ds.data_vars)
                cube_names.append(filepath)
                filename = filepath.split('/')[1]
                sd = pd.to_datetime(str(ds.time.values[0]))
                start_date = sd.strftime('%Y-%m-%d')
                ed = pd.to_datetime(str(ds.time.values[-1]))
                end_date = ed.strftime('%Y-%m-%d')
                chunksize = ds[var_list[0]].data.chunksize
                df = df.append({'cube_name': filename,
                                'chunks (time, lat, lon)': chunksize,
                                'num_vars': len(var_list),
                                'variables': (str(var_list)).replace('[', '').replace(']', '').replace("'", ""),
                                'start_date': start_date,
                                'end_date': end_date}, ignore_index=True)
            except ValueError as e:
                print(filepath)
                print(e)
                pass
```

this results in: 
Screenshot from 2019-09-30 16-38-30

rbins-cmems-SPM-DemoCase-v040_1x128x256_v1.zarr is the newest cube, which I have first pruned and then optimized, and should not be failing.

**Comment by forman** [comment]
> @forman , I have first optimized and then pruned the cubes after PR #195. It was not clear, that pruning had to be done before optimizing...

I didn't say so. I just wanted you to *check* if the order matters.

> Now the PR #195 is already in the master - 

Of course, my fault.

> if I understand your comment correctly, I cannot fix the cubes anymore, because pruning does not work anymore?

No. I was just wondering, whether a possible bug in `xcube prune` could be the cause.

> Because to me it seems, pruning works fine.
> 
> EDIT: Sorry, I think I was confused by your message. I will fix the cubes again.

**Comment by AliceBalfanz** [comment]
The implementation of the PR works fine. The error was on my side, I have optimized the cubes with the branch 0.2.x, where the new changes concerning the xcube optimize where merged into. I accedentally optimized them with master before, so this could not work. Sorry for that.

**Pull request merged**
